
# controller:
#   metrics:
#     port: 10254
#     portName: metrics
#     # if this port is changed, change healthz-port: in extraArgs: accordingly
#     enabled: true
#     service:
#       annotations: 
#         prometheus.io/scrape: "true"
#         prometheus.io/port: "10254"
# #  podAnnotations:
# #    prometheus.io/scrape: "true"
# #    prometheus.io/port: "10254"

#   opentelemetry:
#     enabled: false

controller:
  ingressClassResource:
    name: nginx
    enabled: true
  hostNetwork: true
  kind: DaemonSet
  service:
    type: NodePort
    # TODO: This is needed, because nginx don't know external addresses. Automate it
#    externalIPs:
#      - 13.51.169.11
#      - 13.49.145.25

