
mode: daemonset 

image:
  repository: "otel/opentelemetry-collector-contrib"

presets: 
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines 
  kubernetesAttributes: 
    enabled: true 
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines 
  kubeletMetrics: 
    enabled: true 
  # Enables the filelogreceiver and adds it to the logs pipelines 
  logsCollection: 
    enabled: true 
    includeCollectorLogs: true


config: 
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - 0.0.0.0:8888
  exporters:
    prometheus: 
      endpoint: "0.0.0.0:9090" 
      namespace: "default" 

  service: 
    telemetry: 
      logs: 
        level: "debug" 
      metrics:
        address: 0.0.0.0:8888
    pipelines: 
      metrics: 
        receivers: [prometheus, otlp]
        processors: [batch, memory_limiter]
        exporters: [ prometheus ] 
#      logs: 
#        receivers: [otlp]
#        processors: [batch]
#        exporters: [ otlp, debug ] 

service: 
  enabled: true 
  type: LoadBalancer 
  loadBalancerIP: ""  
#  annotations:    
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
 
ports: 
  prometheus: 
    enabled: true 
    protocol: TCP 
    containerPort: 9090 
    servicePort: 9090 
    hostPort: 9090




